"""room_table


Revision ID: 9f1ef5214721
Revises: 
Create Date: 2019-04-25 15:38:39.895832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1ef5214721'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_code'), 'room', ['code'], unique=True)
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=False)
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_uri', sa.String(length=200), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('current_track', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_current_track'), 'playlist', ['current_track'], unique=False)
    op.create_index(op.f('ix_playlist_playlist_uri'), 'playlist', ['playlist_uri'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_playlist_uri'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_current_track'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_index(op.f('ix_room_code'), table_name='room')
    op.drop_table('room')
    # ### end Alembic commands ###
